kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rotor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", “watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotor
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rotor
subjects:
- kind: ServiceAccount
  name: rotor
  namespace: default
roleRef:
  kind: ClusterRole
  name: rotor
  apiGroup: rbac.authorization.k8s.io
