apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: all-in-one-driver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: all-in-one-driver
    spec:
      containers:
      - image: turbinelabs/all-in-one-driver:0.10.1
        imagePullPolicy: IfNotPresent
        name: all-in-one-driver
        env:
        - name: ALL_IN_ONE_DRIVER_HOST
          value: "<YOUR PUBLIC IP OR HOSTNAME>:80"
        - name: ALL_IN_ONE_DRIVER_LATENCIES
          value: "blue:50ms,green:20ms"
        - name: ALL_IN_ONE_DRIVER_ERROR_RATES
          value: "blue:0.01,green:0.005"
