apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rotor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: rotor
    spec:
      containers:
      - image: turbinelabs/rotor:0.15.1
        imagePullPolicy: Always
        name: rotor
        env:
        - name: ROTOR_CMD
          value: kubernetes
        - name: ROTOR_API_ZONE_NAME
          value: testbed
        - name: ROTOR_API_KEY
          valueFrom:
            secretKeyRef:
              name: tbnsecret
              key: apikey
